### ISSUE TITLE
Size Guide problem

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/ens-merch-shop#100]
**Describe the bug**
Based on below pic it seems some fixes are need to be done on Size Guide table
**To Reproduce**

1. Go to 'https://ens-merch-shop.vercel.app/product/customizable-mens-t-shirt'
2. Scroll down to 'Size Guide'
3. See table

**Screenshots**
<img width="1440" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/111529185/e0570928-e9a4-4b54-8023-70b41e345dd1">

**Expected behavior**

in below pic the all items are shown correctly
<img width="1423" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/111529185/1576f784-815a-48d2-b165-c9a4c60b8c11">

plz check @RamRamez

**Comment by ahmadabugosh** [comment]
Hey @yussdev , I added you on the shopify backend, can you fix these? (you need to edit the product details from shopify directly)

**Comment by yussdev** [comment]
@ahmadabugosh I changed the table, Would you please check it?

**Comment by maryjaf** [comment]
It is better a semi-space to be set in these column 
<img width="481" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/111529185/980eaea3-9736-4c44-8c8a-a3002e660988">

**Comment by ahmadabugosh** [comment]
@yussdev, also can you check all the other products too (since there are a few more that also have size charts that need changing)

**Comment by yussdev** [comment]
@ahmadabugosh  I need the size information for each one for example I'm not sure about these:
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/51474231/b32357a5-f8bd-48dc-bad6-9f828b5572ed)

**Comment by yussdev** [comment]
> It is better a semi-space to be set in these column like "size" cell <img alt="image" width="481" src="https://user-images.githubusercontent.com/111529185/257226253-980eaea3-9736-4c44-8c8a-a3002e660988.png">

Fixed!
