### ISSUE TITLE
Crypto payment issue

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/ens-merch-shop#101]
hey @RamRamez @yussdev 

For some reason Coinbase Commerce gives the error below

<img width="681" alt="Screenshot 2023-07-28 at 4 02 42 PM" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/4855928/430e8fe5-8e01-4929-91d4-d185b3cafc9c">

Can you look into this and see what the error is? It may have to do with our account, so I submitted a request to Coinbase. However, can you check to make sure there are no technical reasons why it's not working?

Also, can you look into alternative apps we can use for Shopify Crypto payments besides Coinbase?

Thanks

**Comment by yussdev** [comment]
Hey @ahmadabugosh I checked this one there are no technical issues on the front side we just redirect the user to the checkout page, all the things are handled by Shopify checkout page
For alternative crypto payments there are more choice that we can integrate like this one:

https://developer.bitpay.com/docs/shopify-plugin

**Comment by ahmadabugosh** [comment]
Thanks @yussdev , I signed up for the new KYC system for Coinbase commerce and Bitpay. I'll keep you posted once I hear back from either of them.

**Comment by ahmadabugosh** [comment]
This has been done, we're Coinbase Commerce is back online
