### ISSUE TITLE
Issue with personalized merch & wrapped domain 

### ISSUE THREAD

**Issue by anaphant** [GeneralMagicio/ens-merch-shop#102]
**Describe the bug**
When trying to purchase [this mug](https://www.ensmerchshop.xyz/product/customizable-ens-mug) with my anpahant.eth ENS, after connecting my wallet, I can't see the desired ENS

**To Reproduce**

1. Go to https://www.ensmerchshop.xyz/product/customizable-ens-mug
2. Connect to the site with this account 0xACEdF0B670DB56Da6731E52841CEa7666D02Ec41
3. Scroll down to ENS name drop down and try to select "anaphant.eth"
4. See error - my ENS doesn't show up

**Screenshots**

![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/100049234/c041265c-cf74-4991-a5f5-76ec4b89e0cb)

**Desktop (please complete the following information):**

-   OS: Linux Ubuntu
-   Browser Brave
-   Version 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)

**Additional context**
I'm trying to get a customized mug but the ENS I want to use is not available in the drop-down because it only shows non wrapped ens domains. (Because the owner of a wrapped domain according to The Graph is wrapper.ens.eth)

**Comment by ahmadabugosh** [comment]
Thanks @anaphant for this! 

@RamRamez @yussdev @MoeNick  Can you please look into this
