### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by ahmadabugosh** [GeneralMagicio/ens-merch-shop#104]
hey @yussdev , 

The contact form on this page doesn't seem to be working anymore, not sure if something changed, can you please look into it? https://www.ensmerchshop.xyz/contact-us and make sure emails go to: info@ensmerchshop.xyz

**Comment by yussdev** [comment]
Hey @ahmadabugosh 
ّIt wasn't working from the beginning. We need to use a third-party mail service for sending email 
There are some:

[Mailgun](https://www.mailgun.com/)

[Amazon SES](https://aws.amazon.com/ses/)

[Twilio SendGrid](https://www.twilio.com/sendgrid)

**Comment by yussdev** [comment]
https://github.com/GeneralMagicio/ens-merch-shop/pull/105
