### ISSUE TITLE
We should use the names of colors instead of the color images

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#107]
Seeing a bug on the unisex hoodie: https://www.ensmerchshop.xyz/product/unisex-hoodie-1

I think we are looking up the color & finding a color image, but shopify is just showing the name. for simplicity, I think we should just put the written name for all variations on all items.
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/75490971/62c9e029-a4a4-494f-9434-2dbb61693deb)

**Comment by RamRamez** [comment]
I fixed it on both product view and sidebar cart view (#112)

**Comment by RamRamez** [comment]
@maryjaf can you test this issue please?

**Comment by laurenluz** [comment]
Hey @RamRamez sorry for this, but quick question..
 How much extra work is it for us to show color previews instead for all?

The reason I asked for text is because that's what shopify is sending, but the colors just look better imo...

But we'd have to have a system for converting the text into the appropriate color icon.

**Comment by RamRamez** [comment]
@laurenluz It's absolutely simple, we have a color map hard coded for this, so I only need to add new colors to our current color map. The point is, each time a new color is added in myshopify (like charcoal), we should hard code it in the code too.

Check them here:
https://github.com/GeneralMagicio/ens-merch-shop/blob/5d23662c8efc2d43c15c099a12215aae6224a360/packages/shopify/src/utils/colors.ts

**Comment by laurenluz** [comment]
oh that is so cool!! tbh, I think this looks much nicer for the user... Also for some of the color codes, I think we should update them to be more accurate (like "khaki").

are you able to add the new adds to the shop into the color codes (e.g. I think we also have grey/black & dusty pink, maybe a few others)? Then we can perhaps revamp this issue to show colors instead of words?

(so sorry for the back & forth, I didn't fully understand what was easy to do here)

**Comment by RamRamez** [comment]
@laurenluz no problem, it's easy to do.

**Comment by RamRamez** [comment]
@laurenluz I reverted last PR and googled the new colors and tried to choose the nearest color. It's live, you can check them.
but, what should we do with the colors like "gray & black" and "gray/black/black"?
and some colors has typo like "carbon grey".

**Comment by maryjaf** [comment]
Is this view for colors is ok?
Combination of color image and name is shown

<img width="1555" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d488a6436e440828b8504e2e5b626d3205aa3197/image.png" alt="image.png" />
and by tapping some of these colors,  in basket the white color is shown, please take a look 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1pSQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1a272099ff1fa54d817463204a9aa5a65b4c882a/Screen%20Recording%202024-02-13%20at%209.40.01%20AM.mov)

**Comment by laurenluz** [comment]
Ideally, they will be all just colors, and no words... so for the Grey/black/black one, we should show like a circle that is half grey and half black.. if possible.

is that possible @RamRamez ?

**Comment by maryjaf** [comment]
> It's fixed. @maryjaf Can you test plz?

Thanks @RamRamez only the color of product in basket should be fixed
<img width="1428" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/111529185/63cdfa0f-b56a-425c-a894-7b673647de00">

**Comment by RamRamez** [comment]
@maryjaf It's fixed, can you test it plz?

**Comment by maryjaf** [comment]
> only the color of product in basket should be fixed

This problem has been resolved
