### ISSUE TITLE
When you click the color, it's not showing the appropriate mockup (as it does in shopify)

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#108]
You can see how it should work by clicking the color variations in the shopify preview for the customizable hat here: https://ens-merch-shop.myshopify.com/products/customizable-hat?variant=47378479776034

when you click the color "khaki" you should see the image of the khaki hat.

And you can see how it's not working here: https://www.ensmerchshop.xyz/product/customizable-hat

**Comment by RamRamez** [comment]
I fixed it for both home page and product page

**Comment by RamRamez** [comment]
@maryjaf can you test it plz?

**Comment by maryjaf** [comment]
Thanks @RamRamez I've echeck and everything is ok

**Comment by laurenluz** [comment]
hoooray!!!!!
