### ISSUE TITLE
Make sure that metadescriptions on our site match product metadescriptions on products

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#109]
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/75490971/36f64319-4c6e-41ec-9e3d-9e9d178f9ee4)

**Comment by RamRamez** [comment]
Done!
I added meta tags for search, 404, about, cart, contact-us, cookies, faq, orders, privacy-policy, profile, refund, terms of use, and wishlist.

**Comment by missgene** [comment]
Hi @RamRamez! I can see that some pages do not have updated meta descriptions yet. Can you check this spreadsheet?
https://docs.google.com/spreadsheets/d/1jq-PNmtghSsNoJAFrRMM2JP87atAofmHgkLbJ21SpZw/edit?usp=sharing 

Also, maybe we need to get @laurenluz's go signal / quick approval for the meta descriptions before adding them to the product pages.

**Comment by missgene** [comment]
Meta descriptions should be longer and SEO-optimized. Character count should be around 120-160 characters. Here is how the meta description of our ENS home page looks like:
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/93360299/4d5e056f-b1e5-4d9e-af0d-d56d6db43298)

**Comment by RamRamez** [comment]
I updated Meta tags for all products on Shopify admin dashboard. Also I updated homepage.
@missgene You can change Meta tags on Shopify admin dashboard on product page (scroll to the end)
https://admin.shopify.com/store/ens-merch-shop/products

@maryjaf can you test it plz?
