### ISSUE TITLE
On the customizable swag, I should only see the domain names I own as options - not rilxxlir.eth!!

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#122]
**Describe the bug**
I am able to buy "customizable" swag for rilxxlir.eth (the default in the designs)... but I my wallet doesn't own this! this shoudl not be possible!!

![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/75490971/3ad9ccd2-0a0f-4f30-b773-fcf68cd137c4)

This is currently a bug on every single customizable option we offer.

**To Reproduce**

1. Go to https://www.ensmerchshop.xyz/search/products
2. Click on Customizable
3. Click any of the options

**Expected behavior**
I should only be able to get customizable swag for ENS names that my address controls... The drop-down menu should only show me "my" domain names as options.

cc @jainkrati @ahmadabugosh

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
I haven't ENS Name now, I would appreciate it if you could check this again @laurenluz

**Comment by laurenluz** [comment]
it;s fixed!
