### ISSUE TITLE
URL on "Customizable" filter is not right

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#123]
**Describe the bug**
if you look at the URL, it says: https://www.ensmerchshop.xyz/search/new-arrivals
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/75490971/61d02a8d-7bc6-45d4-9b6e-dca13d135dd9)

**To Reproduce**

1. Go to https://www.ensmerchshop.xyz/search/products
2. Click on Customizable
3. See error

**Expected behavior**
The URL should say: https://www.ensmerchshop.xyz/search/customizable

I'm not sure if this is a shopify issue that @ahmadabugosh can fix, or if it needs a dev @jainkrati

**Comment by ahmadabugosh** [comment]
@jainkrati I don't see an option to change the URL on shopify, I think this is something we need to do on the frontend side on Vercel

**Comment by RamRamez** [comment]
@ahmadabugosh You can set it by changing the "handle" field in "Search engine listing" section.
I've fixed it so no change is needed now.
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/73441857/ba458922-f40e-4fd4-adba-6b42bfee7a4a)

**Comment by RamRamez** [comment]
@maryjaf to test and verify
