### ISSUE TITLE
Site deprecation - redirect swag shop to https://ens.domains/

### ISSUE THREAD

**Issue by laurenluz** [GeneralMagicio/ens-merch-shop#125]
We are shutting down the shop now (end of April). We should make site simply redirect to https://ens.domains/ - hopefully soon.

cc @ahmadabugosh

**Comment by jainkrati** [comment]
@mhmdksh pls configure the site to redirect to ens url mentioned above.

**Comment by ahmadabugosh** [comment]
@mhmdksh This can be done through Cloudflare

**Comment by geleeroyale** [comment]
I added a redirect rule to direct all traffic to https://ens.domains/

<img width="870" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/317685/ba006155-222a-447c-9edd-7aa0a14436d3">

**Comment by laurenluz** [comment]
beaautiful! I think we can close this, right?
