### ISSUE TITLE
Share Button on Product Pages

### ISSUE THREAD

**Issue by missgene** [GeneralMagicio/ens-merch-shop#42]
### Describe the feature you'd like to request

Clicking the Share button only allows me to copy the link to the product I want to share 

![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/93360299/bf597944-8015-4452-aef6-2522d1336705)

### Describe the solution you'd like

Integrate Social Media Sharing Options: Instead of just enabling users to copy the link, consider integrating direct sharing buttons for popular social media platforms such as Facebook, Twitter, etc. 

Upon clicking these buttons, they should automatically generate a post or tweet featuring the product link, image, and a brief copy/content. This simplifies the process for users to share our products online to their social media accounts. 

### Describe alternatives you've considered

I tried checking on Brave, Safari and Mozilla Firefox. All the same.

**Comment by maryjaf** [comment]
Thanks @RamRamez  share with Facebook, linkedin and twitter have been added  and work correctly 
<img width="1487" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXBNQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bfc1c507d9710d6e8db5ab2c6b0a9e58fb2ade6/image.png" alt="image.png" />
