### ISSUE TITLE
Testing ENS Merch Shop: High delivery price

### ISSUE THREAD

**Issue by brichis** [GeneralMagicio/ens-merch-shop#46]
### Describe the feature you'd like to request

![Screenshot 2023-06-03 at 13 07 01](https://github.com/GeneralMagicio/ens-merch-shop/assets/106570342/01c86d23-81f7-441f-835c-d12155afb58f)
The experience was really smooth, it feel really well to connect your wallet and be able to select any of your ENS. However, I don't know If we can modify that the delivery cost... is expensive, I can buy 3 mugs with the price of delivery. I don't think I would continue with my purchase.

### Describe the solution you'd like

When I was trying in the other site, the delivery was cheaper, I think like 18 USD to the same address.

### Describe alternatives you've considered

Maybe a discount in the delivery price with larger orders. I would prefer using my money in a product than in the delivery.

**Comment by ahmadabugosh** [comment]
This was fixed to automatically take the order time and delivery cost from the supplier (beyond that, there isn't anything we can do to change it at this stage).
