### ISSUE TITLE
Testing ENS Merch Shop: If I click ENS Merch Shop, it send me to the wrong site

### ISSUE THREAD

**Issue by brichis** [GeneralMagicio/ens-merch-shop#47]
### Describe the feature you'd like to request

https://github.com/GeneralMagicio/ens-merch-shop/assets/106570342/047c6b17-3126-403d-b436-b1ffacb79548

### Describe the solution you'd like

I think it should redirect me to: https://ens-merch-shop.vercel.app/

### Describe alternatives you've considered

.

**Comment by brichis** [comment]
The same thing happen If I click the bag of items

**Comment by RamRamez** [comment]
@ahmadabugosh for security reasons, Shopify doesn't allow any code customization on checkout page.

**Comment by ahmadabugosh** [comment]
@RamRamez No worries, in that case can you just redirect the shopify homepage to the ens domain? https://community.shopify.com/c/shopify-design/redirect-home-page-to-collection-page-dawn-theme/m-p/1555955

So for example, set it up so https://ens-merch-shop.myshopify.com/ redirects to https://ensmerchshop.xyz/

**Comment by RamRamez** [comment]
> @RamRamez No worries, in that case can you just redirect the shopify homepage to the ens domain? https://community.shopify.com/c/shopify-design/redirect-home-page-to-collection-page-dawn-theme/m-p/1555955
> 
> So for example, set it up so https://ens-merch-shop.myshopify.com/ redirects to https://ensmerchshop.xyz/

Done!
