### ISSUE TITLE
Testing ENS Shop: The background of the mug image has traces 

### ISSUE THREAD

**Issue by brichis** [GeneralMagicio/ens-merch-shop#49]
### Describe the feature you'd like to request

![Screenshot 2023-06-03 at 13 20 41](https://github.com/GeneralMagicio/ens-merch-shop/assets/106570342/e88f2f7d-7a41-46b2-82e1-2409b570f443)

### Describe the solution you'd like

These white marks should not appear

### Describe alternatives you've considered

A clean crop of the image

**Comment by ahmadabugosh** [comment]
Fixed
