### ISSUE TITLE
Testing ENS Merch Shop: I think I should be able only to see brichis.eth

### ISSUE THREAD

**Issue by brichis** [GeneralMagicio/ens-merch-shop#51]
### Describe the feature you'd like to request

![Screenshot 2023-06-03 at 13 34 09](https://github.com/GeneralMagicio/ens-merch-shop/assets/106570342/8f14e923-b590-4379-989f-0f228f53a2e2)

I think that the customize options should only show the ones I have in my wallet and should not show the option you use as an example.

### Describe the solution you'd like

If I only have brichis.eth I think I should only be able to see brichis.eth

### Describe alternatives you've considered

I think I'll feel it more clean If I'm only able to see brichis.eth because I only have one ENS

**Comment by ahmadabugosh** [comment]
@brichis This is behavior we want to have because rilxxlir.eth is the first ENS name ever made, and we want users to be able to order it (it's also an easter egg)
