### ISSUE TITLE
Testing ENS Merch Shop: If I empty my cart, I get this text

### ISSUE THREAD

**Issue by brichis** [GeneralMagicio/ens-merch-shop#52]
### Describe the feature you'd like to request

![Screenshot 2023-06-03 at 13 38 23](https://github.com/GeneralMagicio/ens-merch-shop/assets/106570342/f264d8e4-6b05-491c-b9d0-42a7e145bfa5)

The text that appears is:
Biscuit oat cake wafer icing ice cream tiramisu pudding cupcake.

### Describe the solution you'd like

I think there could be a text that prompts me to add items to my cart.

### Describe alternatives you've considered

.

**Comment by ahmadabugosh** [comment]
Change this to "Let's add an ENS item to your cart!"
