### ISSUE TITLE
Testing ENS Merch Shop: The Medium link is broken

### ISSUE THREAD

**Issue by brichis** [GeneralMagicio/ens-merch-shop#54]
### Describe the feature you'd like to request

https://github.com/GeneralMagicio/ens-merch-shop/assets/106570342/b433ecd8-7e74-4183-9d0f-9fd55248e198

### Describe the solution you'd like

I want to visit ENS Medium 

### Describe alternatives you've considered

.

**Comment by ahmadabugosh** [comment]
This link is broken on their end, please remove @RamRamez

**Comment by RamRamez** [comment]
I removed medium link
