### ISSUE TITLE
Bug: Connect a Wallet

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/ens-merch-shop#58]
Once I connect the Metamask wallet, I can't change the account after that, is this expected ?

**Comment by RamRamez** [comment]
@maryjaf if you click on your wallet address, you can disconnect.
![image](https://github.com/GeneralMagicio/ens-merch-shop/assets/73441857/406c566a-08c1-4ef1-a26e-6c90772c4e49)

**Comment by ahmadabugosh** [comment]
@RamRamez I noticed this only works if you're on Mainnet. If you connect on Mainnet, then switch your wallet to another network (like Polygon, Optimism, Gnosis etc.) you remain connected, but it doesn't allow you to disconnect your wallet. Maybe we should have an error message that pops up saying swtich to mainnet?
