### ISSUE TITLE
Bug: My Cart

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/ens-merch-shop#60]
I add a product in my cart with user x
 when I log out from user x
 A product is still displayed in the cart 
 
 
<img width="1437" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/111529185/866b71c7-7232-4655-b4a1-ba28a14f2513">

**Comment by ahmadabugosh** [comment]
This is the same issue as the cart not clearing in the cache after a successful order @RamRamez

**Comment by RamRamez** [comment]
@ahmadabugosh we have two sign in and sign out method in the app. Sign in with wallet and sign in with username and password. What is the desired behavior when user signs out of each one?

**Comment by ahmadabugosh** [comment]
@RamRamez I think those are two separate issues. The main thing for this issue is to clear the cart once an order goes through. 

The two sign in options are separate for now, the shopify one lets you view the orders and the wallet one lets you connect your wallet to customize your ENS name.

**Comment by RamRamez** [comment]
@maryjaf since people could check out as a guest, we don't need to delete cart items on log out
