### ISSUE TITLE
Bug: Check out page 

### ISSUE THREAD

**Issue by maryjaf** [GeneralMagicio/ens-merch-shop#61]
I am logged out
when I added some product in my cart by taping on "proceed to checkout" the below pic is shown with my email and my address
<img width="1331" alt="image" src="https://github.com/GeneralMagicio/ens-merch-shop/assets/111529185/da339c48-39f3-40e5-9547-2a1eeec44e21">

**Comment by ahmadabugosh** [comment]
This is the default behavior of Shopify pay, we want to keep this feature.
