### ISSUE TITLE
Testing: Custom items remain in cart across multiple wallets

### ISSUE THREAD

**Issue by 184eth** [GeneralMagicio/ens-merch-shop#63]
### Describe the feature you'd like to request

It's possible to purchase custom items created across different wallets. 

Example: Wallet-1 adds custom-item-A to cart and then disconnects wallet with custom-item-A remaining in cart. Then Wallet-2 connects and adds custom-item-B. 
Result: Both custom-items-A+B remain in cart and can be processed by e.g. Wallet-3 

### Describe the solution you'd like

No action. That feels like a a feature and not a bug.

### Describe alternatives you've considered

Alt 1: The cart is cleared of custom items once a wallet is disconnected: the chalenge with this solution is that disconnecting & reconnecting wallets are often troubleshooting solutions for other issues. 
Alt 2: New signature required on custom-item-A, when wallet-2 is connected.

**Comment by ahmadabugosh** [comment]
This is similar to the other issues with the cart cache @RamRamez
