### ISSUE TITLE
Testing: add measurments/size chart on apparel items 

### ISSUE THREAD

**Issue by 184eth** [GeneralMagicio/ens-merch-shop#64]
### Describe the feature you'd like to request

Add measurements/size chart for apparel 
Reasoning: default European size-M is smaller than default Australian size-M, etc.  

Additional note: add 'one size fits all' on hats/caps

### Describe the solution you'd like

Add a measurements/size chart on items of clothing
e.g. cm/inches for chest, waist, etc

### Describe alternatives you've considered

na

**Comment by ahmadabugosh** [comment]
Added size guides to all products
